### ISSUE TITLE
Help command customization

### ISSUE THREAD

**Issue by gdude2002** [Kotlin-Discord/kord-extensions#49]
It'd be nice to provide something in the `ExtensibleBotBuilder` that exposes a bunch of customization options for the help extension.

It's not known what precisely would be useful here - it'd be nice if the community would weigh in on this.

**Comment by nicholasgrose** [comment]
In my case, I have a constant stream of information in a channel that, for convenience, needs to exist alongside the available commands. However, commands clog up space between the data, so I have added a timeout to many of their results. The ability to add such a timeout to the help command and related behaviour, like argument number, command errors, or the command group help response, would be incredibly helpful.

**Comment by gdude2002** [comment]
Could you be more specific regarding what you meant by the following?

> like argument number, command errors, or the command group help response

**Comment by nicholasgrose** [comment]
> Could you be more specific regarding what you meant by the following?

Sure! I'm referring to the following:
![image](https://user-images.githubusercontent.com/35816886/120390958-5e9fa500-c2fc-11eb-9ba7-e134b0c05cb2.png)
![image](https://user-images.githubusercontent.com/35816886/120390969-63645900-c2fc-11eb-8c5b-96cf800ae43c.png)
![image](https://user-images.githubusercontent.com/35816886/120391007-6cedc100-c2fc-11eb-9812-bdd70f03364d.png)

These messages don't disappear after they are posted nor is there currently an option to make them do so without monitoring the bot's own messages.

**Comment by gdude2002** [comment]
Got it, thanks!

**Comment by gdude2002** [comment]
The commit I've just pushed is specific to the help extension, so it only covers the second screenshot above - I'll get on the rest soonish. For now, please give it a go and let me know what you think!

**Comment by nicholasgrose** [comment]
The new commit has some awesome changes! After playing with it for a little bit, it seems to be doing a great job with timeout of !help and its pages. I also loved the addition of colour. I had never even thought of it, but it is awesome to play with.

There were, however, two issues I noticed. Notably, the help menu for specific commands seems to be unaffected by the timeout. E.g. if I used "!help list", my list command would have its documentation shown but fail to actually disappear. The other is that using `colour { DISCORD_WHITE }` appears to be rendering like `colour { DISCORD_BLACK }`. This might be on Discord's side, though, since they are definitely different in the code. An example of both of these behaviours follows (along with my bot configuration):
![image](https://user-images.githubusercontent.com/35816886/120578655-27142400-c3f4-11eb-8374-073b6c5559d1.png)
![image](https://user-images.githubusercontent.com/35816886/120578705-3e531180-c3f4-11eb-82fc-97856f82f215.png)
The MESSAGE_LIFETIME_MILLIS is 5000, in this case.

**Comment by bosukas** [comment]
For the colour dsl in the help extension, could you provide the MessageCreateEvent or something? I'd like to make the embed colour match the bot's top role colour

**Comment by gdude2002** [comment]
> Wrong colour

I think Discord actually does this whenever you use flat white - I'll update the hex to `FEFEFE` instead of `FFFFFF`, that might work.

> Single pages don't time out

Didn't think of this one - we don't even attempt to wait for an event in this case, so there's nothing to time out, really. I'll fix that.

> MessageCreateEvent

Sure thing!

**Comment by gdude2002** [comment]
I've just pushed - feel free to try it out when you can!

**Comment by nicholasgrose** [comment]
The fixes to make the white look white seem to be working, however the "!help" for specific commands still does not seem to be timing out properly.

**Comment by gdude2002** [comment]
Right you are - I've just tested it out and located the issue. It's working in the test bot now, so please give the next snapshot a go when it builds.

**Comment by nicholasgrose** [comment]
It appears to be working perfectly now! I can't think of any other useful customization options at this time. I will definitely think about it, though.

**Comment by bosukas** [comment]
Small issue, when getting help for subcommands, the menu does not display the full command name
You could fix this by adding a `parentCommand` to the `MessageCommand`, just like you have in `GroupCommand`, so commands can be aware of whether they are subcommands.

Should be `b!test sub1` instead of `b!sub1`
![image](https://user-images.githubusercontent.com/60557521/121816078-6999f400-cc71-11eb-8e9e-00bad966a422.png)

Another small issue i've discovered is that argument types in the `UnionConverter` do not get translated

![image](https://user-images.githubusercontent.com/60557521/121816202-2e4bf500-cc72-11eb-85da-8270408a32c5.png)

**Comment by gdude2002** [comment]
Both problems that @bosukas reported above should be fixed in the latest push.

**Comment by gdude2002** [comment]
At this point, I think we're basically there with this - new issues can be opened for further customisation.
